#!/bin/bash

echo "🚀 GitHub Repository erstellen für tavyro-homepage"
echo ""
echo "Schritt 1: GitHub CLI Login"
echo "Führen Sie zuerst aus: gh auth login"
echo ""
echo "Nach dem Login können Sie das Repository erstellen mit:"
echo ""
echo "gh repo create tavyro-homepage --public --source=. --remote=origin --push"
echo ""
echo "Oder manuell:"
echo "1. Gehen Sie zu https://github.com/new"
echo "2. Repository-Name: tavyro-homepage"
echo "3. Öffentlich (Public) wählen"
echo "4. NICHT 'Initialize with README' ankreuzen"
echo "5. Repository erstellen"
echo "6. Dann ausführen:"
echo "   git remote add origin https://github.com/IHR-USERNAME/tavyro-homepage.git"
echo "   git push -u origin main"
